### ISSUE TITLE
Project Not Compatible with GPL

### ISSUE THREAD

**Issue by skroll** [kakaroto/SWParser#11]
The project has a GPL license, but the decryption code is a compiled binary only. This is not definitely not compatible with the GPL.

Out of curiosity, is there any reason the smon_decrypt library is not available as source?

**Comment by kakaroto** [comment]
I'm the copyright holder, so I'm not actually required to follow the license. More precisely, you can consider it to be double-licensed, GPL for some of the code, and non-GPL for the smon decryptor. Anyways, I was discussing this last night with someone else, and I'm going to relicense it under the LGPL license instead.
As for reasons of not providing the source of that file, it was explained on the reddit announcement post, but I should mention it in the README too. It's because that file basically just contains the decryption key, and I didn't want to make that publicly available to avoid people abusing the game services or creating bots (which is against the terms of use of the game). I also don't want to get Com2Us mad against me for leaking their decryption key.
If it gets publicly released by someone else, then there would be no reason for me to keep it 'hidden' and I'll put the source online.

**Comment by mschettler** [comment]
the only thing that could happen if it's released is com2us changes it and then this entire app won't work until we sniff the new one

**Comment by kakaroto** [comment]
Yeah, and it becomes a game of changing the key every time, which is not useful since a new one can be derived in a matter in a minutes and com2us won't make a release every few minutes. Also, changing the key means it will affect too many parts of their servers, so I think it would be pretty hard for them to update the key (and it may affect every game they have, not just SW, but I'm not sure if they all use the same key).

**Comment by dozens** [comment]
Looks like com2us changed the encryption, hopefully Youness is working on
breaking it again :)

**Comment by skroll** [comment]
It's not like it's really obfuscated anyways, the key can be pulled easily via

```
{ uncompyle2 -d smon_decryptor.pyc | head -n 31; echo "print __var__().encode(\"hex\")" } | python
````
