### ISSUE TITLE
Exception when running on mac

### ISSUE THREAD

**Issue by jeremyfry** [kakaroto/SWParser#23]
I get the following error when running on a Mac using python 2.7.6

```
ERROR - Exception while executing plugin "DemoPlugin": 'command'
Traceback (most recent call last):
  File "SWProxy.py", line 51, in onResponse
    plugin.plugin_object.process_request(req_json, resp_json)
  File "/Users/jfry/Downloads/SWParser-master/plugins/DemoPlugin.py", line 6, in process_request
    print "Found Summoners War API request : %s" % req_json['command']
KeyError: 'command'
```

This is on the login screen very early in the process (Checking for Updates...)

**Comment by lstern** [comment]
this error will not affect anything and will be fixed in the next commit

**Comment by kakaroto** [comment]
Well, there's a couple of things :

* Yes, you should use the latest release instead of downloading the development version (which could be unstable) : https://github.com/kakaroto/SWParser/releases/latest
* BUT, why is this error even happening? the req_json should always have that 'command' value in it!
* Maybe the user was reporting an issue specifically with the dev version to help in the development.

I saw your change which checks if command doesn't exist, it returns, but it was never needed before, so I'm wondering why it would be needed now.

**Comment by lstern** [comment]
The error is occurring before the login request. I don't think its a new error but a error that is now printed on screen (plugins have a try/catch)

**Comment by kakaroto** [comment]
oh, I see, I forgot I had a try/except already in the original code. I guess there's some other data that can go through which doesn't use the command json. In that case, I'd do the check for whether or not 'command' exists inside the plugins, just in case there's a plugin that wants to do something with that packet which doesn't have 'command' in it ?

**Comment by lstern** [comment]
I thought about it and I think that any data transferred before login is
out of this app scope.

**Comment by kakaroto** [comment]
Good point. I was just thinking about a logger plugin that logs everything
and I was curious to know what kind of data doesn't have a command. But
yes, it's better to do the check once rather than in every plugin, and
anything without a command will be considered outside the scope of the app.
